from fastapi import APIRouter
import json
import os
from pathlib import Path

router = APIRouter()

@router.get("/latest")
def get_latest_version():
    """
    Get the latest version information from version.json

    Returns:
        dict: Latest version info including version number and download URLs
    """
    # Read version.json from project root
    version_file = Path(__file__).parent.parent.parent / "version.json"

    if not version_file.exists():
        return {
            "version": "1.0.0",
            "notes": "Version file not found",
            "pub_date": "2025-01-01T00:00:00Z"
        }

    with open(version_file, 'r') as f:
        version_data = json.load(f)

    version = version_data.get("version", "1.0.0")
    changelog = version_data.get("changelog", {})

    # Get the changelog for the current version
    current_changelog = changelog.get(version, {})
    changes = current_changelog.get("changes", [])
    date = current_changelog.get("date", "2025-01-01")

    # Format notes as markdown
    notes = f"# Version {version}\n\n"
    notes += "\n".join([f"- {change}" for change in changes])

    # GitHub release URLs
    github_repo = "albantsrr/ftn-grind"
    base_url = f"https://github.com/{github_repo}/releases/download/v{version}"

    return {
        "version": version,
        "notes": notes,
        "pub_date": f"{date}T00:00:00Z",
        "platforms": {
            "windows-x86_64": {
                "signature": "",  # Will be generated by Tauri
                "url": f"{base_url}/FortiFlow_{version}_x64_en-US.msi"
            }
        }
    }

@router.get("/current")
def get_current_version():
    """
    Get current version from version.json

    Returns:
        dict: Current version number
    """
    version_file = Path(__file__).parent.parent.parent / "version.json"

    if not version_file.exists():
        return {"version": "1.0.0"}

    with open(version_file, 'r') as f:
        version_data = json.load(f)

    return {"version": version_data.get("version", "1.0.0")}
